# Some basic info about your company
company_name: BIG Folio and NextProof
from_email: help@bigfolio.com
support_phone: 805-504-1126

# Your custom field label
custom_label: Dog or cat?

# Can customers attach files?
customer_attachments: false

# Where does your contact link go?
contact: http://www.bigfolio.com/contact

# External links for the top nav section
nav_links:
    - website designs: http://www.bigfolio.com/website-designs
    - company: http://www.bigfolio.com/about
    - testimonials: http://www.bigfolio.com/testimonials
    - contact: http://www.bigfolio.com/contact
    - blog: http://bfstop.bigfolioblog.com/