# Some basic info about your company
company_name: WED Zip
from_email: help@wedzip.com
support_phone: 805-504-1126

# Your custom field label
custom_label: Dog or cat?

# Can customers attach files?
customer_attachments: false

# Where does your contact link go?
contact: http://www.wedzip.com/contact

# External links for the top nav section
nav_links:
    - WED Zip: http://www.wedzip.com
    - Blog: http://blog.wedzip.com